title = "Dániel Árvai"
languageCode = "en-us"
languageName = "English"
weight = 1

[params]
  rssFeedDescription = "full"

[params.author]
  name = "Dániel Árvai"
  avatar = "img/author.jpg"
  intro = "Dániel Árvai"
  description = "Junior Software Engineer"

[params.home]
  recent_posts = "Recent posts"