goToTop = true

[[socialIcons]]
name = "github"
url = "https://github.com/arvaid"

[[socialIcons]]
name = "gitlab"
url = "https://gitlab.com/arvaid"

[[socialIcons]]
name = "email"
url = "contact@arvaid.net"

[[socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/arvaid/"

[[socialIcons]]
name = "Rss"
url = "index.xml"